<a href="https://colab.research.google.com/github/aranyak1/Collab-notebooks/blob/main/1_Numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations


In [2]:
import numpy as np

List vs Numpy Time taken

In [ ]:
from time import process_time

In [ ]:
py_list = [i for i in range(100000)]

start_time = process_time()

py_list = [i+5 for i in py_list]

end_time = process_time()

print(end_time - start_time)

10.471160803


In [ ]:
np_arr = np.array([i for i in range(100000)])

start_time = process_time()

np_arr += 5 # same as np_arr = np_arr + 5 it adds 5 to all the element in a list

end_time = process_time()

print(end_time - start_time)

0.12308107199999796


In [ ]:
np_arr = np.array([1,2,3,4,5])
print(np_arr)
type(np_arr)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
np_arr.shape # Gives Dimensions of the arr

(5,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])

In [ ]:
b.shape

(2, 4)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(b)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders for arrays

In [ ]:
# Creating a numpy array of zeroes

x = np.zeros((4,5)) # (4,5) are dimensions of the array
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# Creating a numpy array of ones

x = np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Creating a numpy array of a given value

x = np.full((3,3),-9)
print(x)

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [ ]:
# Create an identity matrix.Identity matrix is a matrix where diagonal values are 1 and other values are 0 and for identity matrix no of rows are equal to no of cols

y = np.eye(5)
print(y)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Create a np array with random values

z = np.random.random((3,4)) # this will give values between 0 and 1
print(z)

[[0.08495367 0.21580259 0.82506812 0.43605551]
 [0.2912394  0.5138185  0.29246658 0.6217579 ]
 [0.71942103 0.06036613 0.48069219 0.39743511]]


In [ ]:
# Create a np array with random integer values

z = np.random.randint(10,100,(5,6)) # this will give values between 10 and 100
print(z)

[[20 14 22 74 90 14]
 [54 56 76 38 52 22]
 [15 10 25 98 69 94]
 [23 77 52 17 81 77]
 [65 83 48 96 22 39]]


In [ ]:
# Create array of evenly spaced values --> specifying the no of values required

z = np.linspace(10,30,5) # It gives 5 evenly spaced values between 10 and 30
print(z)

[10. 15. 20. 25. 30.]


In [ ]:
# Create array of evenly spaced values --> specifying the step value

z = np.arange(10,30,7)
print(z)

[10 17 24]


In [ ]:
# Convert a list to numpy array

list1 = [1,2,3,4,5]
np_arr = np.asarray(list1)
print(np_arr)

[1 2 3 4 5]


Analyzing a numpy array

In [ ]:
c = np.random.randint(10,50,(3,4))
print(c)

[[38 35 25 21]
 [32 24 27 45]
 [38 19 45 37]]


In [ ]:
print(c.shape)

(3, 4)


In [ ]:
print(c.ndim) # gives no of dimensions

2


In [ ]:
print(c.size) # gives no of elements

12


In [ ]:
# checkin datatype of values in an array
print(c.dtype)

int64


Mathematical operations

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatenates list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(20,30,(3,3))
print(a)
print(b)

[[0 1 9]
 [9 4 2]
 [9 8 8]]
[[25 22 27]
 [25 28 28]
 [25 27 21]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[25 23 36]
 [34 32 30]
 [34 35 29]]
[[-25 -21 -18]
 [-16 -24 -26]
 [-16 -19 -13]]
[[  0  22 243]
 [225 112  56]
 [225 216 168]]
[[0.         0.04545455 0.33333333]
 [0.36       0.14285714 0.07142857]
 [0.36       0.2962963  0.38095238]]


In [ ]:
# We can also do above arithmetic operations like below
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[25 23 36]
 [34 32 30]
 [34 35 29]]
[[-25 -21 -18]
 [-16 -24 -26]
 [-16 -19 -13]]
[[  0  22 243]
 [225 112  56]
 [225 216 168]]
[[0.         0.04545455 0.33333333]
 [0.36       0.14285714 0.07142857]
 [0.36       0.2962963  0.38095238]]


Array manipulation

In [3]:
a = np.random.randint(0,10,(2,3))
print(a)

[[5 5 5]
 [5 3 9]]


In [4]:
trans = np.transpose(a)
print(trans)

[[5 5]
 [5 3]
 [5 9]]


In [6]:
a = np.random.randint(0,10,(2,3))
print(a)

[[6 9 1]
 [1 3 4]]


In [7]:
trans1 = a.T
print(trans1)

[[6 1]
 [9 3]
 [1 4]]


In [9]:
# reshaping an array

z = np.random.randint(0,10,(2,3))
print(z)
print(z.shape)

[[2 9 1]
 [5 8 9]]
(2, 3)


In [11]:
y = z.reshape(3,2)
print(y)
print(y.shape)

[[2 9]
 [1 5]
 [8 9]]
(3, 2)
